{% set version = "1.9.1" %}

package:
  name: geoviews-core
  version: {{ version }}

source:
  url: https://github.com/holoviz/geoviews/archive/v{{ version }}.tar.gz
  sha256: 458bbe40b4bbf7bba5ef7b99d89a28618c024102545bc03687b6659368b335ed

build:
  number: 0

outputs:
  - name: geoviews-core
    script: build_base.sh
    build:
      noarch: python
      entry_points:
        - geoviews = geoviews.__main__:main
    requirements:
      run_constrained:
        - geoviews {{ version }}
      host:
        - python >=3.6
        - pip
        - param >=1.9.0
        # These are also needed at build time and declared in the pyproject.toml
        - pyct >=0.4.4
        - bokeh >=2.3.0,<2.4.0
        - nodejs >=10.13.0
        - wheel
        - cartopy >=0.18.0
        - setuptools >=30.3.0
      run:
        - python >=3.6
        - bokeh >=2.3.0,<2.4.0
        - cartopy >=0.18.0
        - holoviews >=1.14.2
        - numpy  >=1.0
        - param >=1.9.3
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - geoviews

  - name: geoviews
    build:
      noarch: python
    requirements:
      - python >=3.6
      - bokeh >=2.3.0,<2.4.0
      - cartopy >=0.18.0
      - holoviews >=1.14.2
      - numpy >=1.0
      - param >=1.9.3,<2.0
      - {{ pin_subpackage('geoviews-core', max_pin="x.x.x.x") }}
      - datashader
      - geopandas
      - netcdf4
      - pandas
      - pyct
      - xarray
    test:
      imports:
        - geoviews
      requires:
        - nbsmoke
        - pytest
      commands:
        - geoviews examples --path=. --force
        # just run one notebook for now; increase in the future if notebooks can be run quickly with test/tiny data
        - pytest --nbsmoke-run -k ".ipynb" user_guide/Geometries.ipynb
    about:
      home: https://geoviews.org
      license: BSD-3-Clause
      license_file: LICENSE
      summary: GeoViews is a Python library that makes it easy to explore and visualize geographical, meteorological, and oceanographic datasets, such as those used in weather, climate, and remote sensing research.

about:
  home: https://geoviews.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: GeoViews is a Python library that makes it easy to explore and visualize geographical, meteorological, and oceanographic datasets, such as those used in weather, climate, and remote sensing research.
extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
