{% set version = "1.6.6" %}

package:
  name: geoviews-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoviews/geoviews-{{ version }}.tar.gz
  sha256: 5b820b9610f9217327608c5022c9f4223abae335d12c8d9967994ccd17243c6d

build:
  number: 1
  noarch: python

requirements:
  host:
    - python >=2.7
    - pip
    - param >=1.6.1,<2.0
  run:
    - python >=2.7
    - bokeh >=1.0.0
    - cartopy >=0.16.0
    - holoviews >=1.11.1
    - numpy >=1.0
    - param >=1.6.1,<2.0
    - datashader
    - geopandas
    - gdal
    - netcdf4
    - jupyter
    - matplotlib-base >2.2
    - pandas
    - pyct
    - scipy
    - shapely
    - xarray

outputs:
  - name: geoviews-core
    build:
      noarch: python
      script: "{{ PYTHON }} -m pip install . --no-deps -vv"
      entry_points:
        - geoviews = geoviews.__main__:main       
    requirements:
      run_constrained:
        - geoviews {{ version }}
      host:
        - python >=2.7
        - pip
        - param >=1.6.1,<2.0
      run:
        - python >=2.7
        - bokeh >=1.0.0
        - cartopy >=0.16.0
        - holoviews >=1.11.1
        - numpy >=1.0
        - param >=1.6.1,<2.0
    test:
      imports:
        - geoviews

  - name: geoviews
    build:
      noarch: python
    requirements:
      host:
        - python >=2.7
        - pip
        - param >=1.6.1,<2.0
        - geoviews-core {{ version }}
      run:
        - python >=2.7
        - bokeh >=1.0.0
        - cartopy >=0.16.0
        - holoviews >=1.11.1
        - numpy >=1.0
        - param >=1.6.1,<2.0
        - geoviews-core {{ version }}
        - datashader
        - geopandas
        - gdal
        - netcdf4
        - jupyter
        - matplotlib-base >2.2
        - pandas
        - pyct
        - scipy
        - shapely
        - xarray
    test:
      imports:
        - geoviews
      requires:
        - nbsmoke
        - pytest
      commands:
        - geoviews examples --path=. --force
        # just run one notebook for now; increase in the future if notebooks can be run quickly with test/tiny data
        - pytest --nbsmoke-run -k ".ipynb" user_guide/Geometries.ipynb
    about:
      home: http://geoviews.org
      license: BSD-3-Clause
      license_file: LICENSE
      summary: GeoViews is a Python library that makes it easy to explore and visualize
            geographical, meteorological, and oceanographic datasets, such as those used
            in weather, climate, and remote sensing research.

about:
  home: http://geoviews.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: GeoViews is a Python library that makes it easy to explore and visualize
        geographical, meteorological, and oceanographic datasets, such as those used
        in weather, climate, and remote sensing research.
extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
